id: IB4277D01
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:55:17+00:00'
last_modified: '2022-06-08T03:10:48.149239+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30336
  title: གསང་འགྲེལ་སྤར་ཁབ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F1C3:
      image_group_id: I1KG1263
      title: ''
      total_pages: 637
      order: 1
      base_file: F1C3.txt
    5F64:
      image_group_id: I1KG1264
      title: ''
      total_pages: 722
      order: 2
      base_file: 5F64.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
